### ISSUE TITLE
This plugin should conflict with comfyui

### ISSUE THREAD

**Issue by flybirdxx** [Kinglord/ComfyUI_Slider_Sidebar#3]
Hi, after I try to install this plugin, I can't use drag and drop workflow in comfyui to display in comfyui, when I uninstall this plugin, everything becomes normal again, no error message.
![image](https://github.com/user-attachments/assets/6b9b2042-2ac2-4537-8fa4-aad2e06840b9)

https://github.com/user-attachments/assets/7eaed887-20a9-4279-be76-5497bc28833d

https://github.com/user-attachments/assets/3941bf07-5d24-4e83-bd79-04779a2cbb19

**Comment by Kinglord** [comment]
Oops 😭 Sorry about that, will fix this and push up a new version. Let me know if it works afterwards and I can close this.

**Comment by Kinglord** [comment]
This should be fixed in the new version, I tested it out with various images and WF files, let me know if you run into any other issues!

**Comment by flybirdxx** [comment]
> This should be fixed in the new version, I tested it out with various images and WF files, let me know if you run into any other issues!

Thanks to your work, he's running perfectly now.

**Comment by Kinglord** [comment]
Closing as fixed
