### ISSUE TITLE
Error downloading LoRA model: Cannot connect to host civitai.com:443 ssl:default

### ISSUE THREAD

**Issue by RylanLiu** [Kinglord/ComfyUI_Slider_Sidebar#4]
I have filled out the API for my Civitai , but clicking download always fails:Error downloading LoRA model: Cannot connect to host civitai.com:443 ssl:default

I use a VPN proxy and I don't know if that has anything to do with this. There is nothing wrong with my network but it always seems to fail to connect.

**Comment by Kinglord** [comment]
I use a VPN as well so that shouldn't be it. Let me know 2 things and I can troubleshoot a bit more

1. Does this happen on all lora files or just a few?
2. What happens if you leave the API key blank, same thing?

**Comment by RylanLiu** [comment]
> I use a VPN as well so that shouldn't be it. Let me know 2 things and I can troubleshoot a bit more我也使用 VPN，所以不应该这样。让我知道 2 件事，我可以更多地排除故障
> 
> 1. Does this happen on all lora files or just a few?这是发生在所有 lora 文件上还是只发生在几个文件上？
> 2. What happens if you leave the API key blank, same thing?如果您将 API 密钥留空，会发生什么情况？

All lora files failed to connect, and the same thing happened after I deleted the API.

**Comment by lordwedggie** [comment]
same problem here, running on VPN, all sliders fail to download with our without API key
